#!/bin/bash
source _common.sh
source /usr/share/yunohost/helpers

ynh_script_progression "Fjerner tjenesten..."
yunohost service remove "$app"
ynh_systemctl --service="$app" --action="stop"
ynh_config_remove_systemd

ynh_script_progression "Fjerner nginx-konfiguration..."
ynh_config_remove_nginx

ynh_script_progression "Afinstallation fuldført!" --last
